functions:
  - I2C_ADDR
  - 3V3
  - 3V3_S
  - AIN0
  - AIN1
  - BOOT0
  - GND
  - I2C1_SCL
  - I2C1_SDA
  - I2C2_SCL
  - I2C2_SDA
  - IO1
  - IO2
  - IO3
  - IO4
  - IO5
  - IO6
  - IO7
  - IO8
  - LED1
  - LED2
  - LED3
  - RESET
  - RXD0
  - RXD1
  - SPI_CLK
  - SPI_CS
  - SPI_MISO
  - SPI_MOSI
  - SW1
  - TXD0
  - TXD1
  - USB+
  - USB-
  - VBAT
  - VBAT_NRF
  - VBAT_SX
  - VBUS
  - VDD
  - VDD_NRF
  - VIN

slots:
  CORE:
    1: VBAT
    2: VBAT
    3: GND
    4: GND
    5: 3V3
    6: 3V3
    7: USB+
    8: USB-
    9: VBUS
    10: SW1
    11: TXD0
    12: RXD0
    13: RESET
    14: LED1
    15: LED2
    16: LED3
    17: VDD 
    18: VDD 
    19: I2C1_SDA 
    20: I2C1_SCL
    21: AIN0 
    22: AIN1 
    23: BOOT0 
    24: IO7 
    25: SPI_CS
    26: SPI_CLK
    27: SPI_MISO
    28: SPI_MOSI
    29: IO1
    30: IO2
    31: IO3
    32: IO4
    33: TXD1
    34: RXD1
    35: I2C2_SDA
    36: I2C2_SCL
    37: IO5
    38: IO6
    39: GND 
    40: GND
  IO_A:
    1: VBAT
    2: VBAT
    3: GND
    4: GND
    5: 3V3
    6: 3V3_S
    7: USB+
    8: USB-
    9: VBUS
    10: SW1
    11: TXD0
    12: RXD0
    13: RESET
    14: LED1
    15: LED2
    16: LED3
    17: VDD 
    18: VDD 
    19: I2C1_SDA 
    20: I2C1_SCL
    21: AIN0 
    22: AIN1 
    23: NC 
    24: NC
    25: SPI_CS
    26: SPI_CLK
    27: SPI_MISO
    28: SPI_MOSI
    29: IO1
    30: IO2
    31: IO3
    32: IO4
    33: TXD1
    34: RXD1
    35: I2C2_SDA
    36: I2C2_SCL
    37: IO5
    38: IO6
    39: GND 
    40: GND
  IO_B:
    1: VBAT
    2: VBAT
    3: GND
    4: GND
    5: 3V3
    6: 3V3_S
    7: USB+
    8: USB-
    9: VBUS
    10: SW1
    11: TXD0
    12: RXD0
    13: RESET
    14: LED1
    15: LED2
    16: LED3
    17: VDD 
    18: VDD 
    19: I2C1_SDA 
    20: I2C1_SCL
    21: AIN0 
    22: AIN1 
    23: NC 
    24: NC
    25: SPI_CS
    26: SPI_CLK
    27: SPI_MISO
    28: SPI_MOSI
    29: IO1
    30: IO2
    31: IO3
    32: IO4
    33: TXD1
    34: RXD1
    35: I2C2_SDA
    36: I2C2_SCL
    37: IO5
    38: IO6
    39: GND 
    40: GND
  SENSOR_A:
    1: TXD0
    2: GND
    3: SPI_CS
    4: SPI_CLK
    5: SPI_MISO
    6: SPI_MOSI
    7: I2C1_SCL
    8: I2C1_SDA
    9: 3V3
    10: IO2
    11: 3V3_S
    12: IO1
    13: NC
    14: 3V3_S
    15: NC 
    16: 3V3
    17: NC 
    18: NC 
    19: NC 
    20: NC 
    21: NC 
    22: NC 
    23: GND 
    24: RXD0 
  SENSOR_B:
    1: NC
    2: GND
    3: SPI_CS
    4: SPI_CLK
    5: SPI_MISO
    6: SPI_MOSI
    7: I2C1_SCL
    8: I2C1_SDA
    9: 3V3
    10: IO1
    11: 3V3_S
    12: IO2
    13: NC
    14: 3V3_S
    15: NC 
    16: 3V3
    17: NC 
    18: NC 
    19: NC 
    20: NC 
    21: NC 
    22: NC 
    23: GND 
    24: NC 
  SENSOR_C:
    1: NC
    2: GND
    3: SPI_CS
    4: SPI_CLK
    5: SPI_MISO
    6: SPI_MOSI
    7: I2C1_SCL
    8: I2C1_SDA
    9: 3V3
    10: IO4
    11: 3V3_S
    12: IO3
    13: NC
    14: 3V3_S
    15: NC 
    16: 3V3
    17: NC 
    18: NC 
    19: NC 
    20: NC 
    21: NC 
    22: NC 
    23: GND 
    24: NC 
  SENSOR_D:
    1: NC
    2: GND
    3: SPI_CS
    4: SPI_CLK
    5: SPI_MISO
    6: SPI_MOSI
    7: I2C1_SCL
    8: I2C1_SDA
    9: 3V3
    10: IO6
    11: 3V3_S
    12: IO5
    13: NC
    14: 3V3_S
    15: NC 
    16: 3V3
    17: NC 
    18: NC 
    19: NC 
    20: NC 
    21: NC 
    22: NC 
    23: GND 
    24: NC 
  SENSOR_E:
    1: TXD0
    2: GND
    3: SPI_CS
    4: SPI_CLK
    5: SPI_MISO
    6: SPI_MOSI
    7: I2C1_SCL
    8: I2C1_SDA
    9: 3V3
    10: IO3
    11: 3V3_S
    12: IO4
    13: NC
    14: 3V3_S
    15: NC 
    16: 3V3
    17: NC 
    18: NC 
    19: NC 
    20: NC 
    21: NC 
    22: NC 
    23: GND 
    24: RXD0 
  SENSOR_F:
    1: TXD1
    2: GND
    3: SPI_CS
    4: SPI_CLK
    5: SPI_MISO
    6: SPI_MOSI
    7: I2C1_SCL
    8: I2C1_SDA
    9: 3V3
    10: IO5
    11: 3V3_S
    12: IO6
    13: NC
    14: 3V3_S
    15: NC 
    16: 3V3
    17: NC 
    18: NC 
    19: NC 
    20: NC 
    21: NC 
    22: NC 
    23: GND 
    24: RXD1 
  POWER:
    1: VBAT
    2: VBAT
    3: GND
    4: GND
    5: 3V3
    6: 3V3
    7: USB+
    8: USB-
    9: VBUS
    10: VBUS
    11: NC
    12: NC
    13: RESET
    14: LED1
    15: LED2
    16: NC
    17: 3V3
    18: 3V3
    19: I2C1_SDA 
    20: I2C1_SCL
    21: AIN0 
    22: AIN1 
    23: NC 
    24: NC
    25: SPI_CS
    26: SPI_CLK
    27: SPI_MISO
    28: SPI_MOSI
    29: NC
    30: NC
    31: NC
    32: NC
    33: NC
    34: NC
    35: I2C2_SDA
    36: I2C2_SCL
    37: IO5
    38: IO6
    39: GND 
    40: GND

