rak18001:
  mapping:
    10: PWM1 (NC)
  notes:
  - Swap R5 and R6 to change PWM2 to PWM1
rak19002:
  mapping:
    10: EN1 (NC)
  notes:
  - Swap R1 and R3 to change EN2 to EN1
rak11200:
  description: RAK11200 ESP32 WisBlock Core
rak11310:
  description: RAK11310 RP4020 WisBlock Core
rak4631:
  description: RAK4631 nRF52840 WisBlock Core
rak19001:
  type: WisBase
  description: RAK19001 WisBlock Dual IO Base Board
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK19001/
  slots:
    CORE:
      21: ADC_VBAT
    IO_A:
    IO_B:
    SENSOR_A:
    SENSOR_B:
    SENSOR_C:
    SENSOR_D:
    SENSOR_E:
    SENSOR_F:
  notes:  
    - AIN0 is connected to battery (ADC_VBAT)
rak19003:
  type: WisBase
  description: RAK19003 WisBlock Mini Base Board
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK19003/
  slots:
    CORE:
    SENSOR_C:
      1: TXD1
      24: RXD1
    SENSOR_D:
      1: TXD1
      24: RXD1 
rak19007:
  type: WisBase
  description: RAK19007 WisBlock Base Board 2nd Gen
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK19007/
  slots:
    CORE:
    IO_A:
    SENSOR_A:
      1: TXD1
      24: TXD1
    SENSOR_B:
    SENSOR_C:
    SENSOR_D:
      1: TXD1
      24: TXD1
rak19009:
  type: WisBase
  description: RAK19009 WisBlock Mini Base Board with Power Slot
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK19009/
  slots:
    CORE:
    SENSOR_A:
      1: TXD1
      10: IO4
      12: IO3
      24: RXD1
    SENSOR_B:
      1: TXD1
      10: IO6
      12: IO5
      24: RXD1 
    POWER:
rak19010:
  type: WisBase
  description: RAK19010 WisBlock Base Board with Power Slot
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK19010/
  slots:
    CORE:
    IO_A:
    SENSOR_A:
      1: TXD1
      24: TXD1
    SENSOR_B:
    SENSOR_C:
    SENSOR_D:
      1: TXD1
      24: TXD1
    POWER:
rak19011:
  type: WisBase
  description: RAK19001 WisBlock Dual IO Base Board with Power Slot
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK19011/
  slots:
    CORE:
      21: ADC_VBAT
    IO_A:
    IO_B:
    SENSOR_A:
    SENSOR_B:
    SENSOR_C:
    SENSOR_D:
    SENSOR_E:
    SENSOR_F:
    POWER:
  notes:  
    - AIN0 is connected to battery (ADC_VBAT)
rak5005-o:
  type: WisBase
  description: RAK5005-O WisBlock Base Board
  documentation: https://docs.rakwireless.com/Product-Categories/WisBlock/RAK5005-O/
  slots:
    CORE:
    IO_A:
    SENSOR_A:
      1: TXD1
      24: TXD1
    SENSOR_B:
    SENSOR_C:
    SENSOR_D:
