import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'

function triggerDownload(content, filename, mimeType) {
  const blob = new Blob([content], { type: mimeType })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

/**
 * Parse a documentation string into { label, url }.
 * Format: "Description text: https://..."
 */
function formatDate() {
  const d = new Date()
  const yyyy = d.getFullYear()
  const mm = String(d.getMonth() + 1).padStart(2, '0')
  const dd = String(d.getDate()).padStart(2, '0')
  return `${yyyy}/${mm}/${dd}`
}

function parseDocLink(d) {
  const idx = d.lastIndexOf(': http')
  if (idx === -1) return { label: d, url: null }
  return { label: d.slice(0, idx), url: d.slice(idx + 2) }
}

export function exportMarkdown(result, shareUrl) {
  const { columns, slot_module, function_table, conflicts, documentation, notes } = result
  const conflictFns = new Set(conflicts.functions)
  const lines = []

  lines.push('# WisMAP Combine Analysis')
  lines.push('')

  // Build table header
  lines.push('| ' + columns.join(' | ') + ' |')
  lines.push('| ' + columns.map(() => '---').join(' | ') + ' |')

  // MODULE row
  const moduleVals = Object.values(slot_module).map(v => v.toUpperCase())
  lines.push('| MODULE | ' + moduleVals.join(' | ') + ' |')

  // Function rows
  for (const [fn, row] of Object.entries(function_table)) {
    const fnLabel = conflictFns.has(fn) ? `**${row[0]}**` : row[0]
    const cells = [fnLabel, ...row.slice(1)]
    lines.push('| ' + cells.join(' | ') + ' |')
  }

  // Conflicts section
  if (conflicts.notes.length > 0) {
    lines.push('')
    lines.push('## Conflicts')
    lines.push('')
    for (const n of conflicts.notes) {
      lines.push('- ' + n)
    }
  }

  // Notes section
  if (notes.length > 0) {
    lines.push('')
    lines.push('## Notes')
    lines.push('')
    for (const n of notes) {
      lines.push('- ' + n)
    }
  }

  // Documentation section
  if (documentation.length > 0) {
    lines.push('')
    lines.push('## Documentation')
    lines.push('')
    for (const d of documentation) {
      const { label, url } = parseDocLink(d)
      lines.push(url ? `- ${label}: [${url}](${url})` : `- ${label}`)
    }
  }

  lines.push('')
  lines.push('---')
  if (shareUrl) {
    lines.push(`Edit configuration: [${shareUrl}](${shareUrl})`)
    lines.push('')
  }
  lines.push(`*Document generated by WisMAP ${__APP_VERSION__} on ${formatDate()}*`)
  lines.push('')
  triggerDownload(lines.join('\n'), 'wismap-combine.md', 'text/markdown')
}

export function exportPdf(result, shareUrl) {
  const { columns, slot_module, function_table, conflicts, documentation, notes } = result
  const conflictFns = new Set(conflicts.functions)

  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })

  // Title
  doc.setFontSize(16)
  doc.setTextColor(0, 106, 198) // --rak-blue
  doc.text('WisMAP Combine Analysis', 14, 15)

  // Build table data
  const head = [columns]

  const body = []

  // MODULE row
  const moduleRow = ['MODULE', ...Object.values(slot_module).map(v => v.toUpperCase())]
  body.push(moduleRow)

  // Function rows
  for (const [, row] of Object.entries(function_table)) {
    body.push([...row])
  }

  autoTable(doc, {
    head,
    body,
    startY: 20,
    theme: 'grid',
    styles: {
      fontSize: 7,
      cellPadding: 1.5,
      lineColor: [221, 221, 221], // --rak-border
      lineWidth: 0.2,
    },
    headStyles: {
      fillColor: [230, 241, 250], // --rak-blue-light
      textColor: [36, 36, 36],    // --rak-text
      fontStyle: 'bold',
    },
    didParseCell(data) {
      if (data.section !== 'body') return

      // MODULE row (first body row, index 0)
      if (data.row.index === 0) {
        data.cell.styles.fillColor = [230, 241, 250] // --rak-blue-light
        data.cell.styles.fontStyle = 'bold'
        data.cell.styles.textColor = [0, 106, 198]   // --rak-blue
      }

      // Conflict rows and I2C_ADDR styling
      const fnName = data.row.raw[0]
      if (conflictFns.has(fnName)) {
        data.cell.styles.fillColor = [255, 185, 185]  // --rak-gold-light (red-tinted)
        data.cell.styles.textColor = [36, 36, 36]
      } else if (fnName === 'I2C_ADDR') {
        data.cell.styles.fillColor = [240, 240, 240]
        data.cell.styles.textColor = [102, 102, 102]  // --rak-text-muted
        data.cell.styles.fontStyle = 'italic'
      }
    },
  })

  // Notes and conflicts below the table
  let y = doc.lastAutoTable.finalY + 8

  if (conflicts.notes.length > 0 || notes.length > 0) {
    doc.setFontSize(11)
    doc.setTextColor(102, 102, 102)
    doc.text('Notes', 14, y)
    y += 5

    doc.setFontSize(8)
    for (const n of conflicts.notes) {
      doc.setTextColor(225, 0, 0)
      if (y > 190) { doc.addPage(); y = 15 }
      doc.text('- ' + n, 16, y)
      y += 4
    }

    doc.setTextColor(36, 36, 36)
    for (const n of notes) {
      if (y > 190) { doc.addPage(); y = 15 }
      doc.text('- ' + n, 16, y)
      y += 4
    }
  }

  // Documentation
  if (documentation.length > 0) {
    y += 3
    doc.setFontSize(11)
    doc.setTextColor(102, 102, 102)
    if (y > 190) { doc.addPage(); y = 15 }
    doc.text('Documentation', 14, y)
    y += 5

    doc.setFontSize(8)
    doc.setTextColor(36, 36, 36)
    for (const d of documentation) {
      const { label, url } = parseDocLink(d)
      if (y > 190) { doc.addPage(); y = 15 }
      const text = url ? `- ${label}: ${url}` : `- ${label}`
      doc.text(text, 16, y)
      y += 4
    }
  }

  // Shareable link
  if (shareUrl) {
    y += 4
    if (y > 280) { doc.addPage(); y = 15 }
    doc.setFontSize(8)
    doc.setTextColor(0, 106, 198)
    doc.textWithLink(`Edit configuration: ${shareUrl}`, 14, y, { url: shareUrl })
    y += 4
  }

  // Footnote
  y += 2
  if (y > 280) { doc.addPage(); y = 15 }
  doc.setFontSize(8)
  doc.setTextColor(102, 102, 102)
  doc.text(`Document generated by WisMAP ${__APP_VERSION__} on ${formatDate()}`, 14, y)

  doc.save('wismap-combine.pdf')
}
