import { jsPDF } from 'jspdf'
import autoTable from 'jspdf-autotable'
import { triggerDownload, formatDate } from './exportUtils.js'

export function exportModuleMarkdown(info) {
  const lines = []
  const id = info.id.toUpperCase()

  lines.push(`# ${id}`)
  lines.push('')

  lines.push(`- **Type:** ${info.type}`)
  lines.push(`- **Description:** ${info.description}`)
  if (info.documentation) {
    lines.push(`- **Documentation:** [${info.documentation}](${info.documentation})`)
  }
  if (info.double !== null) {
    lines.push(`- **Long (double):** ${info.double ? 'Yes' : 'No'}`)
  }
  if (info.i2c_address) {
    lines.push(`- **I2C Address:** ${info.i2c_address}`)
  }
  if (info.tags && info.tags.length > 0) {
    lines.push(`- **Tags:** ${info.tags.join(', ')}`)
  }

  if (info.notes && info.notes.length > 0) {
    lines.push('')
    lines.push('## Notes')
    lines.push('')
    for (const n of info.notes) {
      lines.push(`- ${n}`)
    }
  }

  if (info.mapping && info.mapping.length > 0) {
    lines.push('')
    lines.push('## Pin Mapping')
    lines.push('')
    lines.push('| PIN | Function |')
    lines.push('| --- | --- |')
    for (const r of info.mapping) {
      lines.push(`| ${r.pin} | ${r.function} |`)
    }
  }

  if (info.slots_table) {
    lines.push('')
    lines.push('## Slot Pin Mapping')
    lines.push('')
    const cols = ['PIN', ...info.slots_table.columns]
    lines.push('| ' + cols.join(' | ') + ' |')
    lines.push('| ' + cols.map(() => '---').join(' | ') + ' |')
    for (const row of info.slots_table.rows) {
      const cells = [row.pin, ...info.slots_table.columns.map(c => row[c] || '')]
      lines.push('| ' + cells.join(' | ') + ' |')
    }
  }

  if (info.schematics && info.schematics.length > 0) {
    lines.push('')
    lines.push('## Schematics')
    lines.push('')
    for (const url of info.schematics) {
      lines.push(`![${id} schematic](${url})`)
      lines.push('')
    }
  }

  if (info.images && info.images.length > 0) {
    lines.push('')
    lines.push('## Images')
    lines.push('')
    for (const url of info.images) {
      lines.push(`![${id}](${url})`)
      lines.push('')
    }
  }

  lines.push('---')
  lines.push(`*Document generated by WisMAP ${__APP_VERSION__} on ${formatDate()}*`)
  lines.push('')

  triggerDownload(lines.join('\n'), `wismap-${info.id}.md`, 'text/markdown')
}

async function loadImage(url) {
  // Use server-side proxy to avoid CORS issues with remote images
  const proxyUrl = `/api/image-proxy?url=${encodeURIComponent(url)}`
  try {
    const resp = await fetch(proxyUrl)
    if (!resp.ok) return null
    const blob = await resp.blob()
    const dataUrl = await new Promise((resolve, reject) => {
      const reader = new FileReader()
      reader.onload = () => resolve(reader.result)
      reader.onerror = reject
      reader.readAsDataURL(blob)
    })
    // Decode to get dimensions
    const img = new Image()
    await new Promise((resolve, reject) => {
      img.onload = resolve
      img.onerror = reject
      img.src = dataUrl
    })
    return {
      dataUrl,
      width: img.naturalWidth,
      height: img.naturalHeight,
    }
  } catch {
    return null
  }
}

export async function exportModulePdf(info) {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' })
  const id = info.id.toUpperCase()
  const margin = 14
  const contentWidth = 210 - margin * 2
  const font = 'helvetica'

  // ── Title ──
  doc.setFont(font, 'bold')
  doc.setFontSize(18)
  doc.setTextColor(0, 106, 198) // --rak-blue
  doc.text(id, margin, 18)

  // ── Metadata table ──
  const metaRows = [
    ['Type', info.type],
    ['Description', info.description],
  ]
  if (info.documentation) metaRows.push(['Documentation', info.documentation])
  if (info.double !== null) metaRows.push(['Long (double)', info.double ? 'Yes' : 'No'])
  if (info.i2c_address) metaRows.push(['I2C Address', info.i2c_address])
  if (info.tags && info.tags.length > 0) metaRows.push(['Tags', info.tags.join(', ')])

  autoTable(doc, {
    body: metaRows,
    startY: 22,
    theme: 'plain',
    styles: {
      font: font,
      fontSize: 9,
      cellPadding: { top: 1.5, bottom: 1.5, left: 2, right: 2 },
      textColor: [36, 36, 36],
    },
    columnStyles: {
      0: { fontStyle: 'bold', cellWidth: 32 },
    },
  })
  let y = doc.lastAutoTable.finalY + 8

  // ── Notes ──
  if (info.notes && info.notes.length > 0) {
    if (y > 265) { doc.addPage(); y = 15 }
    doc.setFont(font, 'bold')
    doc.setFontSize(12)
    doc.setTextColor(0, 106, 198)
    doc.text('Notes', margin, y)
    y += 5

    doc.setFont(font, 'normal')
    doc.setFontSize(9)
    doc.setTextColor(36, 36, 36)
    for (const n of info.notes) {
      if (y > 275) { doc.addPage(); y = 15 }
      const lines = doc.splitTextToSize('- ' + n, contentWidth - 4)
      doc.text(lines, margin + 2, y)
      y += lines.length * 4
    }
    y += 3
  }

  // ── Pin mapping table ──
  if (info.mapping && info.mapping.length > 0) {
    y += 4
    if (y > 265) { doc.addPage(); y = 15 }
    doc.setFont(font, 'bold')
    doc.setFontSize(12)
    doc.setTextColor(0, 106, 198)
    doc.text('Pin Mapping', margin, y)
    y += 2

    autoTable(doc, {
      head: [['PIN', 'Function']],
      body: info.mapping.map(r => [r.pin, r.function]),
      startY: y,
      theme: 'grid',
      styles: {
        font: font,
        fontSize: 8,
        cellPadding: 2,
        lineColor: [221, 221, 221],
        lineWidth: 0.2,
        textColor: [36, 36, 36],
      },
      headStyles: {
        fillColor: [230, 241, 250],
        textColor: [36, 36, 36],
        fontStyle: 'bold',
      },
      alternateRowStyles: { fillColor: [248, 248, 248] },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  // ── Slot pin mapping table ──
  if (info.slots_table) {
    y += 4
    if (y > 265) { doc.addPage(); y = 15 }
    doc.setFont(font, 'bold')
    doc.setFontSize(12)
    doc.setTextColor(0, 106, 198)
    doc.text('Slot Pin Mapping', margin, y)
    y += 2

    autoTable(doc, {
      head: [['PIN', ...info.slots_table.columns]],
      body: info.slots_table.rows.map(row => [
        row.pin,
        ...info.slots_table.columns.map(c => row[c] || ''),
      ]),
      startY: y,
      theme: 'grid',
      styles: {
        font: font,
        fontSize: 7,
        cellPadding: 1.5,
        lineColor: [221, 221, 221],
        lineWidth: 0.2,
        textColor: [36, 36, 36],
      },
      headStyles: {
        fillColor: [230, 241, 250],
        textColor: [36, 36, 36],
        fontStyle: 'bold',
      },
      alternateRowStyles: { fillColor: [248, 248, 248] },
    })
    y = doc.lastAutoTable.finalY + 6
  }

  // ── Schematics & Images ──
  const allImages = [
    ...(info.schematics || []).map(url => ({ url, label: 'Schematics' })),
    ...(info.images || []).map(url => ({ url, label: 'Images' })),
  ]

  let currentLabel = null
  for (const { url, label } of allImages) {
    const isNewSection = label !== currentLabel

    const imgData = await loadImage(url)
    if (!imgData) continue

    const maxW = contentWidth
    const maxH = 130
    let w = imgData.width * 0.264583 // px to mm at 96 dpi
    let h = imgData.height * 0.264583
    if (w > maxW) { h = h * (maxW / w); w = maxW }
    if (h > maxH) { w = w * (maxH / h); h = maxH }

    // Space needed: section heading (if new) + image
    const headingSpace = isNewSection ? 9 : 0 // extra gap + title + gap
    if (y + headingSpace + h > 280) { doc.addPage(); y = 15 }

    if (isNewSection) {
      currentLabel = label
      y += 4
      doc.setFont(font, 'bold')
      doc.setFontSize(12)
      doc.setTextColor(0, 106, 198)
      doc.text(label, margin, y)
      y += 5
    }

    doc.addImage(imgData.dataUrl, margin, y, w, h)
    y += h + 5
  }

  // ── Footer ──
  y += 4
  if (y > 280) { doc.addPage(); y = 15 }
  doc.setFont(font, 'normal')
  doc.setFontSize(8)
  doc.setTextColor(150, 150, 150)
  doc.text(`Document generated by WisMAP ${__APP_VERSION__} on ${formatDate()}`, margin, y)

  doc.save(`wismap-${info.id}.pdf`)
}
